/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.ui.contentassist;

import com.beenleigh.dsl.ui.contentassist.AbstractLemmaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LemmaProposalProvider extends AbstractLemmaProposalProvider {
}
