/*
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LemmaStandaloneSetup extends LemmaStandaloneSetupGenerated {

	def static void doSetup() {
		new LemmaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
