/*
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.ui.tests;

import com.beenleigh.lemma.ui.internal.LemmaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class LemmaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LemmaActivator.getInstance().getInjector("com.beenleigh.dsl.Lemma");
	}

}
