/*
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.ui;

import com.beenleigh.lemma.ui.internal.LemmaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LemmaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LemmaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LemmaActivator.getInstance().getInjector(LemmaActivator.COM_BEENLEIGH_DSL_LEMMA);
	}
	
}
