/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl;

import com.beenleigh.dsl.LemmaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LemmaStandaloneSetup extends LemmaStandaloneSetupGenerated {
  public static void doSetup() {
    LemmaStandaloneSetup _lemmaStandaloneSetup = new LemmaStandaloneSetup();
    _lemmaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
