/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma.impl;

import com.beenleigh.dsl.lemma.AbstractItem;
import com.beenleigh.dsl.lemma.LemmaPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractItemImpl extends MinimalEObjectImpl.Container implements AbstractItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LemmaPackage.Literals.ABSTRACT_ITEM;
  }

} //AbstractItemImpl
