/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma.impl;

import com.beenleigh.dsl.lemma.ContainerElement;
import com.beenleigh.dsl.lemma.DataClass;
import com.beenleigh.dsl.lemma.LemmaPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Class</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.beenleigh.dsl.lemma.impl.DataClassImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.beenleigh.dsl.lemma.impl.DataClassImpl#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link com.beenleigh.dsl.lemma.impl.DataClassImpl#getDataelements <em>Dataelements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataClassImpl extends AbstractItemImpl implements DataClass
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSuperType() <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperType()
   * @generated
   * @ordered
   */
  protected DataClass superType;

  /**
   * The cached value of the '{@link #getDataelements() <em>Dataelements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataelements()
   * @generated
   * @ordered
   */
  protected EList<ContainerElement> dataelements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataClassImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LemmaPackage.Literals.DATA_CLASS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LemmaPackage.DATA_CLASS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataClass getSuperType()
  {
    if (superType != null && superType.eIsProxy())
    {
      InternalEObject oldSuperType = (InternalEObject)superType;
      superType = (DataClass)eResolveProxy(oldSuperType);
      if (superType != oldSuperType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, LemmaPackage.DATA_CLASS__SUPER_TYPE, oldSuperType, superType));
      }
    }
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataClass basicGetSuperType()
  {
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSuperType(DataClass newSuperType)
  {
    DataClass oldSuperType = superType;
    superType = newSuperType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LemmaPackage.DATA_CLASS__SUPER_TYPE, oldSuperType, superType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ContainerElement> getDataelements()
  {
    if (dataelements == null)
    {
      dataelements = new EObjectContainmentEList<ContainerElement>(ContainerElement.class, this, LemmaPackage.DATA_CLASS__DATAELEMENTS);
    }
    return dataelements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LemmaPackage.DATA_CLASS__DATAELEMENTS:
        return ((InternalEList<?>)getDataelements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LemmaPackage.DATA_CLASS__NAME:
        return getName();
      case LemmaPackage.DATA_CLASS__SUPER_TYPE:
        if (resolve) return getSuperType();
        return basicGetSuperType();
      case LemmaPackage.DATA_CLASS__DATAELEMENTS:
        return getDataelements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LemmaPackage.DATA_CLASS__NAME:
        setName((String)newValue);
        return;
      case LemmaPackage.DATA_CLASS__SUPER_TYPE:
        setSuperType((DataClass)newValue);
        return;
      case LemmaPackage.DATA_CLASS__DATAELEMENTS:
        getDataelements().clear();
        getDataelements().addAll((Collection<? extends ContainerElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LemmaPackage.DATA_CLASS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LemmaPackage.DATA_CLASS__SUPER_TYPE:
        setSuperType((DataClass)null);
        return;
      case LemmaPackage.DATA_CLASS__DATAELEMENTS:
        getDataelements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LemmaPackage.DATA_CLASS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LemmaPackage.DATA_CLASS__SUPER_TYPE:
        return superType != null;
      case LemmaPackage.DATA_CLASS__DATAELEMENTS:
        return dataelements != null && !dataelements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == ContainerElement.class)
    {
      switch (derivedFeatureID)
      {
        case LemmaPackage.DATA_CLASS__NAME: return LemmaPackage.CONTAINER_ELEMENT__NAME;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == ContainerElement.class)
    {
      switch (baseFeatureID)
      {
        case LemmaPackage.CONTAINER_ELEMENT__NAME: return LemmaPackage.DATA_CLASS__NAME;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //DataClassImpl
