/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma.impl;

import com.beenleigh.dsl.lemma.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LemmaFactoryImpl extends EFactoryImpl implements LemmaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static LemmaFactory init()
  {
    try
    {
      LemmaFactory theLemmaFactory = (LemmaFactory)EPackage.Registry.INSTANCE.getEFactory(LemmaPackage.eNS_URI);
      if (theLemmaFactory != null)
      {
        return theLemmaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new LemmaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LemmaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case LemmaPackage.LEMMAMODEL: return createLemmamodel();
      case LemmaPackage.DATA_MODEL: return createDataModel();
      case LemmaPackage.ABSTRACT_ITEM: return createAbstractItem();
      case LemmaPackage.IMPORT: return createImport();
      case LemmaPackage.DATA_TYPE: return createDataType();
      case LemmaPackage.CONTAINER_ELEMENT: return createContainerElement();
      case LemmaPackage.DATA_CLASS: return createDataClass();
      case LemmaPackage.DATA_ELEMENT: return createDataElement();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lemmamodel createLemmamodel()
  {
    LemmamodelImpl lemmamodel = new LemmamodelImpl();
    return lemmamodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataModel createDataModel()
  {
    DataModelImpl dataModel = new DataModelImpl();
    return dataModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AbstractItem createAbstractItem()
  {
    AbstractItemImpl abstractItem = new AbstractItemImpl();
    return abstractItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType createDataType()
  {
    DataTypeImpl dataType = new DataTypeImpl();
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ContainerElement createContainerElement()
  {
    ContainerElementImpl containerElement = new ContainerElementImpl();
    return containerElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataClass createDataClass()
  {
    DataClassImpl dataClass = new DataClassImpl();
    return dataClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataElement createDataElement()
  {
    DataElementImpl dataElement = new DataElementImpl();
    return dataElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LemmaPackage getLemmaPackage()
  {
    return (LemmaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static LemmaPackage getPackage()
  {
    return LemmaPackage.eINSTANCE;
  }

} //LemmaFactoryImpl
