/*
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLemmaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.beenleigh.dsl.lemma.LemmaPackage.eINSTANCE);
		return result;
	}
	
}
