/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.web;

import com.beenleigh.dsl.web.AbstractLemmaWebModule;
import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LemmaWebModule extends AbstractLemmaWebModule {
  public LemmaWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
