/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.web;

import com.beenleigh.dsl.LemmaStandaloneSetup;
import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LemmaWebSetup extends LemmaStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  public LemmaWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
