/*
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.parser.antlr;

import com.beenleigh.dsl.parser.antlr.internal.InternalLemmaParser;
import com.beenleigh.dsl.services.LemmaGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LemmaParser extends AbstractAntlrParser {

	@Inject
	private LemmaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLemmaParser createParser(XtextTokenStream stream) {
		return new InternalLemmaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Lemmamodel";
	}

	public LemmaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LemmaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
