/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Item</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.beenleigh.dsl.lemma.LemmaPackage#getAbstractItem()
 * @model
 * @generated
 */
public interface AbstractItem extends EObject
{
} // AbstractItem
