/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.beenleigh.dsl.lemma.DataModel#getName <em>Name</em>}</li>
 *   <li>{@link com.beenleigh.dsl.lemma.DataModel#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataModel()
 * @model
 * @generated
 */
public interface DataModel extends AbstractItem
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.beenleigh.dsl.lemma.DataModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.beenleigh.dsl.lemma.AbstractItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractItem> getElements();

} // DataModel
