/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.beenleigh.dsl.lemma.DataClass#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link com.beenleigh.dsl.lemma.DataClass#getDataelements <em>Dataelements</em>}</li>
 * </ul>
 *
 * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataClass()
 * @model
 * @generated
 */
public interface DataClass extends AbstractItem, ContainerElement
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(DataClass)
   * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataClass_SuperType()
   * @model
   * @generated
   */
  DataClass getSuperType();

  /**
   * Sets the value of the '{@link com.beenleigh.dsl.lemma.DataClass#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(DataClass value);

  /**
   * Returns the value of the '<em><b>Dataelements</b></em>' containment reference list.
   * The list contents are of type {@link com.beenleigh.dsl.lemma.ContainerElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataelements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataelements</em>' containment reference list.
   * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataClass_Dataelements()
   * @model containment="true"
   * @generated
   */
  EList<ContainerElement> getDataelements();

} // DataClass
