/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.beenleigh.dsl.lemma.DataElement#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataElement()
 * @model
 * @generated
 */
public interface DataElement extends ContainerElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DataType)
   * @see com.beenleigh.dsl.lemma.LemmaPackage#getDataElement_Type()
   * @model
   * @generated
   */
  DataType getType();

  /**
   * Sets the value of the '{@link com.beenleigh.dsl.lemma.DataElement#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DataType value);

} // DataElement
