/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.lemma;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lemmamodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.beenleigh.dsl.lemma.Lemmamodel#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see com.beenleigh.dsl.lemma.LemmaPackage#getLemmamodel()
 * @model
 * @generated
 */
public interface Lemmamodel extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.beenleigh.dsl.lemma.AbstractItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see com.beenleigh.dsl.lemma.LemmaPackage#getLemmamodel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractItem> getElements();

} // Lemmamodel
