/*
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLemmaScopeProvider extends DelegatingScopeProvider {
}
