/**
 * generated by Xtext 2.10.0
 */
package com.beenleigh.dsl.ui;

import com.beenleigh.dsl.ui.AbstractLemmaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LemmaUiModule extends AbstractLemmaUiModule {
  public LemmaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
